import { useEffect, useState } from "react";
import { api, type AIUsageSummary, type FeatureFlag, type ProviderModel } from "../api/client";
import { Badge, Empty, ErrorState, Loading } from "../components/States";
import { Button } from "../components/ui/Button";
import { Tabs, TabPanel } from "../components/ui/Tabs";
import { useToast } from "../components/ui/Toast";

export default function AdminV2Governance(){
  const toast=useToast();const [flags,setFlags]=useState<FeatureFlag[]>([]);const [models,setModels]=useState<ProviderModel[]>([]);const [usage,setUsage]=useState<AIUsageSummary|null>(null);const [tab,setTab]=useState("features");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [busy,setBusy]=useState("");
  async function load(){setLoading(true);setError("");try{const [flagResult,modelResult,usageResult]=await Promise.allSettled([api.featureFlags(),api.providerModels(),api.aiUsage()]);if(flagResult.status==="fulfilled")setFlags(flagResult.value.items);if(modelResult.status==="fulfilled")setModels(modelResult.value.items);if(usageResult.status==="fulfilled")setUsage(usageResult.value);if([flagResult,modelResult,usageResult].every(result=>result.status==="rejected"))throw new Error("No V2 governance module is available for this account.")}catch(e){setError(e instanceof Error?e.message:"Unable to load V2 governance")}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  async function killSwitch(flag:FeatureFlag){setBusy(flag.key);try{await api.updateFeatureFlag(flag.key,{kill_switch:!flag.kill_switch,reason:`${!flag.kill_switch?"Activate":"Release"} emergency kill switch from Admin governance UI`});await load();toast(`Kill switch ${!flag.kill_switch?"activated":"released"}.`,!flag.kill_switch?"danger":"success")}catch(e){toast(e instanceof Error?e.message:"Unable to update feature","danger")}finally{setBusy("")}}
  if(loading)return <div className="content"><Loading label="Loading V2 governance…"/></div>;
  if(error&&!flags.length&&!models.length)return <div className="content"><ErrorState message={error} onRetry={load}/></div>;
  return <div className="content"><div className="page-title"><div><p className="eyebrow">TicketSense V2 control plane</p><h1>AI governance</h1><p>Server-enforced feature rollout, immutable model versions and measured provider usage.</p></div><div className="live"><span/>No sample metrics</div></div>
    <Tabs idPrefix="v2-governance" active={tab} onChange={setTab} tabs={[{key:"features",label:"Feature flags"},{key:"models",label:"Model registry"},{key:"usage",label:"Observability"}]}/>
    <TabPanel id="v2-governance" tabKey="features" active={tab}><div className="panel governance-table"><div className="list-head governance-row"><span>Feature</span><span>Owner</span><span>Evaluation</span><span>Safety</span></div>{flags.map(flag=><article className="list-row governance-row" key={flag.key}><div><b>{flag.key.replaceAll("_"," ")}</b><small>{flag.description}</small>{flag.prerequisites.length>0&&<small>Requires: {flag.prerequisites.join(", ")}</small>}</div><span>{flag.owner}</span><div><Badge value={flag.evaluation.enabled?"enabled":"disabled"}/><small>{flag.evaluation.reason}</small></div><Button size="sm" variant={flag.kill_switch?"primary":"destructive"} loading={busy===flag.key} onClick={()=>killSwitch(flag)}>{flag.kill_switch?"Release kill switch":"Kill switch"}</Button></article>)}</div></TabPanel>
    <TabPanel id="v2-governance" tabKey="models" active={tab}>{models.length?<div className="panel governance-table"><div className="list-head model-registry-row"><span>Task / model</span><span>Immutable version</span><span>Role</span><span>Status</span></div>{models.map(model=><article className="list-row model-registry-row" key={model.id}><div><b>{model.task_type}</b><small>{model.provider_type} · {model.model_identifier}</small></div><code>{model.immutable_version}</code><Badge value={model.lifecycle_role}/><div><Badge value={model.enabled?model.evaluation_status:"disabled"}/><small>{model.deployment_environment} · {model.data_residency_policy}</small></div></article>)}</div>:<Empty label="No provider/model versions are registered for this tenant."/>}</TabPanel>
    <TabPanel id="v2-governance" tabKey="usage" active={tab}>{usage?.groups.length?<div className="panel governance-table"><div className="list-head usage-row"><span>Provider task</span><span>Calls</span><span>Latency</span><span>Measured cost</span></div>{usage.groups.map(group=><article className="list-row usage-row" key={`${group.task_type}-${group.provider}-${group.model_version}`}><div><b>{group.task_type}</b><small>{group.provider} · {group.model_version}</small></div><strong>{group.calls}</strong><span>p50 {group.latency_ms.p50} ms · p95 {group.latency_ms.p95} ms</span><span>{group.measured_cost_usd==null?"Unavailable":`$${group.measured_cost_usd.toFixed(4)}`}</span></article>)}</div>:<Empty label={usage?.empty_state||"No measured provider usage exists."}/>}</TabPanel>
  </div>
}
